friends=['Andrey', 'Ilya', 'Vlad']
print('Hello',friends[0],'! Come to the meeting at 5.')
print('Hello',friends[1],'! Come to the meeting at 5.')
print('Hello',friends[2],'! Come to the meeting at 5.')
print()
print(friends[2], 'wosnt be able to come(')
friends[2]='Valia'
print()
print('Hello',friends[0],'! Come to the meeting at 5.')
print('Hello',friends[1],'! Come to the meeting at 5.')
print('Hello',friends[2],'! Come to the meeting at 5.')
print()
print('The guest list has expanded!')
print()
friends.insert(0, 'Leva')
friends.insert(2, 'Kiril')
friends.append('Misha')
print(friends)
print()
print('Hello',friends[0],'! Come to the meeting at 5.')
print('Hello',friends[1],'! Come to the meeting at 5.')
print('Hello',friends[2],'! Come to the meeting at 5.')
print('Hello',friends[3],'! Come to the meeting at 5.')
print('Hello',friends[4],'! Come to the meeting at 5.')
print('Hello',friends[5],'! Come to the meeting at 5.')
